### ISSUE TITLE
cannot use ibllib after installation data_exploration_gui Error Starting Kernel

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/ibllib#130]
After installation iblapps-develop to use data_exploration_gui (https://github.com/int-brain-lab/iblapps/tree/develop/data_exploration_gui) it seems there is some problem with _ibllib_. 
I am having this error when I try to open my script that previously was working fine:
I am on master branch and use ibllib repo
```
Error Starting Kernel

Traceback (most recent call last):
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\jupyter_client\connect.py", line 470, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\jupyter_core\paths.py", line 430, in secure_write
    win32_restrict_file_to_user(fname)
  File "d:\ibl\programs\anaconda3\envs\ibllib\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.
OK
```

**Comment by oliche** [comment]
Could you try:

pip uninstall pypiwin32
pip install pywin32

**Comment by karolinasocha** [comment]
It did not work.

**Comment by oliche** [comment]
In that case, especially given that you're on Windows it's probably easier
to re-install a new environment from scratch to see if you still have the
issue.
