### ISSUE TITLE
Error after command : source run_tests 

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#15]
I followed the information on this page to install ibllib: https://ibllib.readthedocs.io/en/latest/02_installation.html
I am having these errors (Note: I am on Mac).

```
(gaellework) MBP-de-Gaelle:python gaellechapuis$ source run_tests
EE..         
======================================================================
ERROR: test_download_datasets (ibllib.tests.test_alyxclient.TestDownloadHTTP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10af8ce48>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test.alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10af8ce48>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/tests/test_alyxclient.py", line 15, in setUp
    base_url=par.BASE_URL)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/webclient.py", line 151, in __init__
    self.authenticate(**kwargs)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/webclient.py", line 167, in authenticate
    data=dict(username=username, password=password))
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10af8ce48>: Failed to establish a new connection: [Errno 60] Operation timed out',))

======================================================================
ERROR: test_download_datasets_with_api (ibllib.tests.test_alyxclient.TestDownloadHTTP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10afacc18>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test.alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10afacc18>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/tests/test_alyxclient.py", line 15, in setUp
    base_url=par.BASE_URL)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/webclient.py", line 151, in __init__
    self.authenticate(**kwargs)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/webclient.py", line 167, in authenticate
    data=dict(username=username, password=password))
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10afacc18>: Failed to establish a new connection: [Errno 60] Operation timed out',))

----------------------------------------------------------------------
Ran 4 tests in 150.124s

FAILED (errors=2)
Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x114c53160>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test.alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x114c53160>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/oneibl/tests/test_one_tutorial.py", line 1, in <module>
    import oneibl.examples.tutorial_script
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/oneibl/examples/tutorial_script.py", line 5, in <module>
    password='TapetesBloc18')
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/oneibl/one.py", line 67, in __init__
    self._alyxClient = wc.AlyxClient(username=username, password=password, base_url=base_url)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/webclient.py", line 151, in __init__
    self.authenticate(**kwargs)
  File "/Users/gaellechapuis/Documents/gitClones/ibllib/python/ibllib/webclient.py", line 167, in authenticate
    data=dict(username=username, password=password))
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/gaellechapuis/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.alyx.internationalbrainlab.org', port=443): Max retries exceeded with url: /auth-token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x114c53160>: Failed to establish a new connection: [Errno 60] Operation timed out',))
(gaellework) MBP-de-Gaelle:python gaellechapuis$ 

```

**Comment by oliche** [comment]
Since you posted this late in the evening, I assume you attempted this from home. The ports to the server are only opened from participating institutions, so if you attempt behind a VPN or at work this will go through.

Arguably the error could be more concise and telling as well. Done on a new feature branch, for the next release.

**Comment by GaelleChapuis** [comment]
Ok thanks, will try again. It was not clear from the documentation that I
needed to be connected to institution network though.

Gaelle
