### ISSUE TITLE
one=ONE() URL error

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/ibllib#31]
This is what I have in python prompt
one = ONE()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\IBL\Programs\Anaconda3\envs\ibllib\python\oneibl\one.py", line 84, in __init__
    base_url=base_url)
  File "D:\IBL\Programs\Anaconda3\envs\ibllib\python\oneibl\webclient.py", line 154, in __init__
    self.authenticate(**kwargs)
  File "D:\IBL\Programs\Anaconda3\envs\ibllib\python\oneibl\webclient.py", line 192, in authenticate
    data=dict(username=username, password=password))
  File "D:\IBL\Programs\Anaconda3\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\IBL\Programs\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\IBL\Programs\Anaconda3\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "D:\IBL\Programs\Anaconda3\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\IBL\Programs\Anaconda3\lib\site-packages\requests\models.py", line 309, in prepare
    self.prepare_url(url, params)
  File "D:\IBL\Programs\Anaconda3\lib\site-packages\requests\models.py", line 383, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'one /auth-token': No schema supplied. Perhaps you meant http://one /auth-token?

**Comment by oliche** [comment]
The Alyx address is wrong, it should be https://alyx.internationalbrainlab.org. Need to check the parameter file or re-run `ONE.setup()`
