### ISSUE TITLE
ImportError: Failed to import test module: test_alyxclient / test_one / test_one_tutorial

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/ibllib#32]
Karolina and I are running the test from the documentation and we get the same error (see below)

My parameter file is the following:

```
    "ALYX_LOGIN": "Gaelle",
    "ALYX_PWD": --hidden for github,
    "ALYX_URL": "https://alyx.internationalbrainlab.org",
    "CACHE_DIR": "C:\\Users\\Experiment\\Downloads\\FlatIron",
    "FTP_DATA_SERVER": "ftp://ibl.flatironinstitute.org",
    "FTP_DATA_SERVER_LOGIN": "iblftp",
    "FTP_DATA_SERVER_PWD": --hidden for github
    "HTTP_DATA_SERVER": "http://ibl.flatironinstitute.org",
    "HTTP_DATA_SERVER_LOGIN": "iblmember",
    "HTTP_DATA_SERVER_PWD": --hidden for github
    "GLOBUS_CLIENT_ID": null
```

```
(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python>call run_tests.bat

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python>cd .\ibllib\tests

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests>python -m unittest discover
.EE
======================================================================
ERROR: test_io (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_io
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests\test_io.py", line 5, in <module>
    import ibllib.io.params as params
ModuleNotFoundError: No module named 'ibllib'


======================================================================
ERROR: test_time (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_time
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests\test_time.py", line 2, in <module>
    import ibllib.time
ModuleNotFoundError: No module named 'ibllib'


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=2)

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests>cd ..\..\oneibl\tests

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests>python -m unittest discover
EEE
======================================================================
ERROR: test_alyxclient (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_alyxclient
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests\test_alyxclient.py", line 4, in <module>
    import oneibl.webclient as wc
ModuleNotFoundError: No module named 'oneibl'


======================================================================
ERROR: test_one (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_one
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests\test_one.py", line 3, in <module>
    from oneibl.one import ONE
ModuleNotFoundError: No module named 'oneibl'


======================================================================
ERROR: test_one_tutorial (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_one_tutorial
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests\test_one_tutorial.py", line 1, in <module>
    import oneibl.examples.tutorial_script
ModuleNotFoundError: No module named 'oneibl'


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests>cd..

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl>cd..

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python>call run_tests.bat

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python>cd .\ibllib\tests

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests>python -m unittest discover
.EE
======================================================================
ERROR: test_io (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_io
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests\test_io.py", line 5, in <module>
    import ibllib.io.params as params
ModuleNotFoundError: No module named 'ibllib'


======================================================================
ERROR: test_time (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_time
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests\test_time.py", line 2, in <module>
    import ibllib.time
ModuleNotFoundError: No module named 'ibllib'


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=2)

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\ibllib\tests>cd ..\..\oneibl\tests

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests>python -m unittest discover
EEE
======================================================================
ERROR: test_alyxclient (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_alyxclient
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests\test_alyxclient.py", line 4, in <module>
    import oneibl.webclient as wc
ModuleNotFoundError: No module named 'oneibl'


======================================================================
ERROR: test_one (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_one
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests\test_one.py", line 3, in <module>
    from oneibl.one import ONE
ModuleNotFoundError: No module named 'oneibl'


======================================================================
ERROR: test_one_tutorial (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_one_tutorial
Traceback (most recent call last):
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Experiment\AppData\Local\Continuum\miniconda3\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests\test_one_tutorial.py", line 1, in <module>
    import oneibl.examples.tutorial_script
ModuleNotFoundError: No module named 'oneibl'


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)

(ibllibenv) C:\Users\Experiment\Documents\GitFolder\ibllib\python\oneibl\tests>


```

**Comment by oliche** [comment]
I can't reproduce this on Unix. I need to go back to my Windows laptop to reproduce this, I know it's possible that after pip install, there is discrepancies in import resolution between the 2 OS.

I would recommend to switch back to the master branch for the time being, as this one is safe on Windows.

**Comment by oliche** [comment]
Followed instructions step by step with users and couldn't reproduce bug.
