### ISSUE TITLE
logging error in alf extraction

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/ibllib#44]
```>conda activate iblenv   && python C:\ibllib\python\alf\one_iblrig.py extract D:\globus_server\Subjects   && python C:\ibllib\python\alf\one_iblrig.py register D:\globus_server\Subjects
2019-02-05 20:59:19.887 INFO     [extract_session.py:64] Extracting D:\globus_server\Subjects\IBL_1\2019-02-05\001
2019-02-05 21:01:14.7 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.feedbackType.npy
2019-02-05 21:01:14.23 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.contrastLeft.npy
2019-02-05 21:01:14.29 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.contrastRight.npy
2019-02-05 21:01:14.35 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.probabilityLeft.npy
2019-02-05 21:01:14.41 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.choice.npy
2019-02-05 21:01:14.46 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.repNum.npy
2019-02-05 21:01:14.52 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.rewardVolume.npy
2019-02-05 21:01:14.59 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.feedback_times.npy
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not WindowsPath
Call stack:
  File "C:\ibllib\python\alf\one_iblrig.py", line 99, in <module>
    extract(args.folder, dry=args.dry)
  File "C:\ibllib\python\alf\one_iblrig.py", line 25, in extract
    extract_session.bulk(root_data_folder, dry=dry)
  File "c:\ibllib\python\alf\extract_session.py", line 84, in bulk
    from_path(p.parent, force=True, save=save)
  File "c:\ibllib\python\alf\extract_session.py", line 30, in func_wrapper
    f = func(sessionpath, *args, **kwargs)
  File "c:\ibllib\python\alf\extract_session.py", line 70, in from_path
    training_trials.extract_all(session_path, save=save)
  File "c:\ibllib\python\alf\extractors\training_trials.py", line 529, in extract_all
    stimOn_times = get_stimOn_times(session_path, save=save, data=data)
  File "c:\ibllib\python\alf\extractors\training_trials.py", line 322, in get_stimOn_times
    count_missing, session_path)
Message: '%s: Missing BNC1 stimulus on %i trials'
Arguments: (77, WindowsPath('D:/globus_server/Subjects/IBL_1/2019-02-05/001'))
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 1034, in emit
    msg = self.format(record)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 880, in format
    return fmt.format(record)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\site-packages\colorlog\colorlog.py", line 119, in format
    message = super(ColoredFormatter, self).format(record)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 619, in format
    record.message = record.getMessage()
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\logging\__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not WindowsPath
Call stack:
  File "C:\ibllib\python\alf\one_iblrig.py", line 99, in <module>
    extract(args.folder, dry=args.dry)
  File "C:\ibllib\python\alf\one_iblrig.py", line 25, in extract
    extract_session.bulk(root_data_folder, dry=dry)
  File "c:\ibllib\python\alf\extract_session.py", line 84, in bulk
    from_path(p.parent, force=True, save=save)
  File "c:\ibllib\python\alf\extract_session.py", line 30, in func_wrapper
    f = func(sessionpath, *args, **kwargs)
  File "c:\ibllib\python\alf\extract_session.py", line 70, in from_path
    training_trials.extract_all(session_path, save=save)
  File "c:\ibllib\python\alf\extractors\training_trials.py", line 529, in extract_all
    stimOn_times = get_stimOn_times(session_path, save=save, data=data)
  File "c:\ibllib\python\alf\extractors\training_trials.py", line 322, in get_stimOn_times
    count_missing, session_path)
Message: '%s: Missing BNC1 stimulus on %i trials'
Arguments: (77, WindowsPath('D:/globus_server/Subjects/IBL_1/2019-02-05/001'))
2019-02-05 21:01:14.265 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.stimOn_times.npy
2019-02-05 21:01:14.270 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.intervals.npy
2019-02-05 21:01:14.279 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.response_times.npy
2019-02-05 21:01:14.672 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.itiDuration.npy
2019-02-05 21:01:14.678 INFO     [raw_data_loaders.py:290] extracting_ibl_trials.included
2019-02-05 21:01:16.6 INFO     [raw_data_loaders.py:290] extracting_ibl_wheel.timestamps.npy
2019-02-05 21:01:16.18 INFO     [raw_data_loaders.py:290] extracting_ibl_wheel.position.npy
2019-02-05 21:01:16.41 INFO     [raw_data_loaders.py:290] extracting_ibl_wheel.velocity.npy
2019-02-05 21:01:16.81 INFO     [extract_session.py:72] session extracted```

**Comment by oliche** [comment]
Fixed in 227b0e5028680c35e57eb8ccdd696fa6aff4e201
