### ISSUE TITLE
No module named 'spikeglx'

### ISSUE THREAD

**Issue by MCangelov** [int-brain-lab/ibllib#482]
I am following the guide for the "BL ephys alignment GUI installation, creating the environment from scratch.
Right at the end, where I have to launch the GUI using
`python int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py -o True`
I get the following error:

> (iblenv) C:\Users\Neuw Gao\int-brain-lab\iblapps\atlaselectrophysiology>python ephys_atlas_gui.py -o True
> Traceback (most recent call last):
>   File "C:\Users\Neuw Gao\int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 13, in <module>
>     from atlaselectrophysiology.load_data import LoadData
>   File "C:\Users\Neuw Gao\int-brain-lab\iblapps\atlaselectrophysiology\load_data.py", line 4, in <module>
>     import ibllib.pipes.histology as histology
>   File "C:\Users\Neuw Gao\int-brain-lab\ibllib-repo\ibllib\pipes\__init__.py", line 5, in <module>
>     from ibllib.io.flags import FLAG_FILE_NAMES
>   File "C:\Users\Neuw Gao\int-brain-lab\ibllib-repo\ibllib\io\__init__.py", line 1, in <module>
>     import spikeglx
> ModuleNotFoundError: No module named 'spikeglx'

I've tried using both the iblapps/ibllib master and develop commit, however the issue persists.
Any suggestions how to tackle this?

**Comment by mayofaulkner** [comment]
Hi, could you try 
`pip install ibl-neuropixel`

**Comment by MCangelov** [comment]
Thanks for the quick reply Mayo,
using `pip install ibl-neuropixel` I get the following:

> (iblenv) C:\Users\Neuw Gao\int-brain-lab>python iblapps\atlaselectrophysiology\ephys_atlas_gui.py -o True
> Traceback (most recent call last):
>   File "C:\Users\Neuw Gao\int-brain-lab\iblapps\atlaselectrophysiology\ephys_atlas_gui.py", line 13, in <module>
>     from atlaselectrophysiology.load_data import LoadData
>   File "C:\Users\Neuw Gao\int-brain-lab\iblapps\atlaselectrophysiology\load_data.py", line 4, in <module>
>     import ibllib.pipes.histology as histology
>   File "C:\Users\Neuw Gao\int-brain-lab\ibllib-repo\ibllib\pipes\histology.py", line 10, in <module>
>     import ibllib.atlas as atlas
>   File "C:\Users\Neuw Gao\int-brain-lab\ibllib-repo\ibllib\atlas\__init__.py", line 1, in <module>
>     from .atlas import *  # noqa
>   File "C:\Users\Neuw Gao\int-brain-lab\ibllib-repo\ibllib\atlas\atlas.py", line 8, in <module>
>     import boto3
> ModuleNotFoundError: No module named 'boto3'
