### ISSUE TITLE
Corrupted session end time in the bpod rig output data

### ISSUE THREAD

**Issue by valagui** [int-brain-lab/ibllib#53]
Trying to run `TRANSFER_2_SERVER.bat` and it gives me this error:
```Traceback (most recent call last):
  File "C:\ibllib\python\alf\one_iblrig.py", line 108, in <module>
    create(args.folder, dry=args.dry)
  File "C:\ibllib\python\alf\one_iblrig.py", line 41, in create
    rc.create_sessions(root_data_folder, dry=dry)
  File "c:\ibllib\python\oneibl\registration.py", line 48, in create_sessions
    status_str = self.register_session(flag_file.parent, file_list=False)
  File "c:\ibllib\python\oneibl\registration.py", line 24, in func_wrapper
    f = func(self, sessionpath, *args, **kwargs)
  File "c:\ibllib\python\oneibl\registration.py", line 119, in register_session
    end_time = start_time + datetime.timedelta(seconds=ses_duration_secs)
OverflowError: date value out of range```

**Comment by oliche** [comment]
@nbonacchi  This is a Bpod issue, and it's a big concern.
It already happened in CSHL for IBL_36 on rig 1 on the 29th of January   when we watered mice in the future:
https://alyx.internationalbrainlab.org/admin/actions/session/60ead1ba-0817-455d-9926-1d9002df1c16/change/

@valagui I'll need to get the data for this one.

**Comment by oliche** [comment]
C:\iblrig_data\Subjects\IBL_46\2019-02-19\001
