### ISSUE TITLE
print_progress' from 'ibllib.misc

### ISSUE THREAD

**Issue by MCangelov** [int-brain-lab/ibllib#543]
I'm trying to convert the ephys data as described in https://github.com/int-brain-lab/iblapps/wiki/4.-Preparing-data-for-ephys-GUI however when I run 'from atlaselectrophysiology.extract_files import extract_data' I get the following error.

```
Python 3.9.15 (main, Nov 23 2022, 09:27:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> from atlaselectrophysiology.extract_files import extract_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\neuw gao\iblapps\atlaselectrophysiology\extract_files.py", line 11, in <module>
    from ibllib.misc import print_progress
ImportError: cannot import name 'print_progress' from 'ibllib.misc' (C:\Users\Neuw Gao\.conda\envs\iblenv\lib\site-packages\ibllib\misc\__init__.py)
```
Any suggestions?

**Comment by k1o0** [comment]
Hello I've fixed the issue.  Please run `git pull` to update to the latest changes from iblapps. Please feel free to reopen this issue if necessary.
