### ISSUE TITLE
Table index error from 'list_datasets(...)' when ONE sets 'cache_dir'

### ISSUE THREAD

**Issue by CodyCBakerPhD** [int-brain-lab/ibllib#564]
**Before posting** 
Make sure your environment is fully up-to-date by running 
```
conda activate iblenv
conda env update --file iblenv.yaml --prune
```

See #563 

I'm working in

```
ONE-api==1.19.1
ibllib==2.20.0
```

as the primary dependencies in two closely related environments - the following error only occurs in one of them however.

I've attached complete `pip freeze` info for both environments, labeled correspondingly.

For background, the 'faulty' one followed `iblenv` installation instructions to the letter as a base, and then installed a handful of extra packages required that I need for handling the data after loading it through `ibllib`.

The 'good' one is instead a randomly chosen 3.8 base used primary by the AllenSDK, which then installed the `ONE-api` and `ibllib` versions mentioned above.

[faulty_environment_one_table_issue.txt](https://github.com/int-brain-lab/ibllib/files/10561434/faulty_environment_one_table_issue.txt)

[good_environment_one_table_issue.txt](https://github.com/int-brain-lab/ibllib/files/10561435/good_environment_one_table_issue.txt)

**Describe the bug**

In the faulty environment, if you initialize an `ONE` with only a single keyword argument `cache_dir="some/path"`, I get a strange table index error when attempting to query something simple like

```
python -c "from one.api import ONE; one=ONE(cache_dir="some/path"); res=one.list_datasets(eid='ae8787b1-4229-4d56-b0c2-566b61a25b77', collection='raw_ephys_data/*')"
```

fails with traceback

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/iblenv/lib/python3.9/site-packages/one/util.py", line 170, in wrapper
    return method(self, *args, **kwargs)
  File "/home/jovyan/my-conda-envs/iblenv/lib/python3.9/site-packages/one/api.py", line 712, in list_datasets
    if self._index_type() is int:
  File "/home/jovyan/my-conda-envs/iblenv/lib/python3.9/site-packages/one/api.py", line 592, in _index_type
    idx_0 = table.index.values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

coming from the call to `list_datasets`

**Expected behavior**

It works if you let the `cache_dir` use the default

```
python -c "from one.api import ONE; one=ONE(); res=one.list_datasets(eid='ae8787b1-4229-4d56-b0c2-566b61a25b77', collection='raw_ephys_data/*'); print(res)"
```

but I'd like to have control over the cache location.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 22.04.1

**Comment by CodyCBakerPhD** [comment]
Ahh, aside from the confusion as to how this does or does not work magically depending on the environment, it also seems like it might be an issue with allowing full defaults in `ONE()`

If I do

```
python -c "from one.api import ONE; one=ONE(base_url='https://openalyx.internationalbrainlab.org', password='international', silent=True, cache_dir='/some/path'); res=one.list_datasets(eid='ae8787b1-4229-4d56-b0c2-566b61a25b77', collection='raw_ephys_data/*'); print(res)"
```

then it works even in the 'faulty' environment and uses the correct cache.

So I'm guessing there's a subtle difference somewhere between using

```python
ONE(cache_dir='/some/path')
```

and

```python
ONE(base_url='https://openalyx.internationalbrainlab.org', password='international', silent=True, cache_dir='/some/path')
```

that causes this problem

**Comment by CodyCBakerPhD** [comment]
Also, even more context for a separate traceback that occurs when you try to use `ONE()` defaults + `cache_dir` in yet another environment

This was discovered in a CI, here's the full log: https://github.com/SpikeInterface/spikeinterface/actions/runs/4075858310/jobs/7022817671

```
    one = ONE(cache_dir=cache_folder)
../../../test_env/lib/python3.9/site-packages/one/api.py:1361: in ONE
    return OneAlyx(mode=mode, wildcards=wildcards, **kwargs)
../../../test_env/lib/python3.9/site-packages/one/api.py:1402: in __init__
    self._web_client = wc.AlyxClient(username=username,
../../../test_env/lib/python3.9/site-packages/one/webclient.py:500: in __init__
    self._par = one.params.get(client=base_url, silent=self.silent, username=username)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = None, silent = False, username = None

    def get(client=None, silent=False, username=None):
        """Returns the AlyxClient parameters
    
        Parameters
        ----------
        silent : bool
            If true, defaults are chosen if no parameters found.
        client : str
            The database URL to retrieve parameters for.  If None, the default is loaded.
        username : str
            The username to use.  If None, the default is loaded.
    
        Returns
        -------
        IBLParams
            A Params object for the AlyxClient.
        """
        client_key = _key_from_url(client) if client else None
        cache_map = iopar.read(f'{_PAR_ID_STR}/{_CLIENT_ID_STR}', {})
        # If there are no params for this client, run setup routine
        if not cache_map or (client_key and client_key not in cache_map.CLIENT_MAP):
            cache_map = setup(client=client, silent=silent, username=username)
>       cache = cache_map.CLIENT_MAP[client_key or cache_map.DEFAULT]
E       AttributeError: 'IBLParams' object has no attribute 'DEFAULT'
```

but I've also never seen this one locally
