### ISSUE TITLE
can't create the session on Alyx for DY_003

### ISSUE THREAD

**Issue by ibldan** [int-brain-lab/ibllib#58]
I just start the training for DY_003 in my third rig. After run the habituation today, I try to transfer the data to local server, but it showed an error like this (and I can transfer DY_002's data in this rig):
`(base) C:\Users\IBLuser>conda activate iblenv

(iblenv) C:\Users\IBLuser>python C:\ibllib\python\alf\one_iblrig.py create C:\iblrig_data\Subjects
Connected to https://alyx.internationalbrainlab.org as feihu
2019-03-09 13:21:06.11 INFO     [registration.py:46] creating session for C:\iblrig_data\Subjects\DY_002\2019-03-02\001
2019-03-09 13:21:12.937 ERROR    [webclient.py:173] https://alyx.internationalbrainlab.org/sessions
2019-03-09 13:21:12.941 ERROR    [webclient.py:174] {"location":["Object with name=iblrig_danlab_behavior_3 does not exist."]}
Traceback (most recent call last):
  File "C:\ibllib\python\alf\one_iblrig.py", line 108, in <module>
    create(args.folder, dry=args.dry)
  File "C:\ibllib\python\alf\one_iblrig.py", line 41, in create
    rc.create_sessions(root_data_folder, dry=dry)
  File "c:\ibllib\python\oneibl\registration.py", line 48, in create_sessions
    status_str = self.register_session(flag_file.parent, file_list=False)
  File "c:\ibllib\python\oneibl\registration.py", line 24, in func_wrapper
    f = func(self, sessionpath, *args, **kwargs)
  File "c:\ibllib\python\oneibl\registration.py", line 151, in register_session
    session = self.one.alyx.rest('sessions', 'create', data=ses_)
  File "c:\ibllib\python\oneibl\webclient.py", line 347, in rest
    return self.post('/' + endpoint, data)
  File "c:\ibllib\python\oneibl\webclient.py", line 262, in post
    return self._generic_request(requests.post, rest_query, data=data)
  File "c:\ibllib\python\oneibl\webclient.py", line 175, in _generic_request
    raise Exception(r)
Exception: <Response [400]>`

**Comment by ibldan** [comment]
the data information (including body weight and water intake) in this rig are not showed in the Alyx .  DY_002 (March 02) and DY_003 (March 09)

I checked the one, the .one param is correct in this rig

**Comment by oliche** [comment]
2019-03-09 13:21:12.941 ERROR [webclient.py:174] {"location":["Object with name=iblrig_danlab_behavior_3 does not exist."]}

On Alyx, https://alyx.internationalbrainlab.org/admin/misc/lablocation/261c71f3-0933-4ac8-9f12-b6ce2dca7961/change/, the location has a trailing underscore:

So on your iblrig setup/parameters, the rig identifier should be `_iblrig_danlab_behavior_3`, and not `iblrig_danlab_behavior_3`

**Comment by ibldan** [comment]
I renamed Box name  in the window, but the error is still there. Where I should modify the parameters?

**Comment by oliche** [comment]
In the file 
`raw_behavior_data/_iblrig_taskSettings.raw.json`, for example:
`/datadisk/00_TEST_DATA/Subjects/ZM_1087/2019-01-25/002/raw_behavior_data/_iblrig_taskSettings.raw.json`

You need to change this line (should be around line 88)
`"PYBPOD_BOARD": "_iblrig_mainenlab_behavior_1",`

And then re-run the registration.
