### ISSUE TITLE
Bug when trying to create session on Alyx

### ISSUE THREAD

**Issue by jeanpaulnc** [int-brain-lab/ibllib#67]
(iblenv) C:\iblrig>python C:\ibllib\python\alf\one_iblrig.py create C:\iblrig_data\Subjects
Connected to https://alyx.internationalbrainlab.org as jeanpaul
2019-04-10 12:19:42.188 INFO     [registration.py:47] creating session for C:\iblrig_data\Subjects\IBL-T4\2019-03-26\001
Traceback (most recent call last):
  File "C:\ibllib\python\alf\one_iblrig.py", line 108, in <module>
    create(args.folder, dry=args.dry)
  File "C:\ibllib\python\alf\one_iblrig.py", line 41, in create
    rc.create_sessions(root_data_folder, dry=dry)
  File "c:\ibllib\python\oneibl\registration.py", line 49, in create_sessions
    status_str = self.register_session(flag_file.parent, file_list=False)
  File "c:\ibllib\python\oneibl\registration.py", line 24, in func_wrapper
    f = func(self, sessionpath, *args, **kwargs)
  File "c:\ibllib\python\oneibl\registration.py", line 90, in register_session
    md = _read_settings_json_compatibility_enforced(settings_json_file)
  File "c:\ibllib\python\oneibl\registration.py", line 236, in _read_settings_json_compatibility_enforced
    md = json.load(js)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(iblenv) C:\iblrig>python C:\ibllib\python\alf\one_iblrig.py create C:\iblrig_data\Subject
Traceback (most recent call last):
  File "C:\ibllib\python\alf\one_iblrig.py", line 102, in <module>
    assert(Path(args.folder).exists())
AssertionError

**Comment by oliche** [comment]
So `_iblrig_taskSettings.raw.json` file is empty.
It's not a bug. Moved this on Slack.
