### ISSUE TITLE
 [registration.py:47] creating session for wrong animal

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/ibllib#69]
**Describe the bug**
In IBL training rig1 there is no generated extract file in the end of the session:
![image](https://user-images.githubusercontent.com/32096962/56045630-7e00a000-5d39-11e9-991b-54e3cd56545b.png)
For some reason, in the end of the training (trainingChoiceWorld protocol), the session is created for wrong animal (in this case KS001_NPx instead of KS004). KS001_NPx- that is not included to IBL project (but he exists in cortexlab alyx),and the rig 1 was used for habituation. 

I tried several times to start new session for KS001 but I have all the time the same bug in the end that it tries to create session for KS001_NPx.

**Screenshots**
```
2019-04-12 15:45:22.55 INFO     [session_params.py:204]
##########################################
PREVIOUS SESSION FOUND
LOADING PARAMETERS FROM: C:\iblrig_data\Subjects\KS004\2019-04-12\001\raw_behavior_data\_iblrig_taskData.raw.jsonable

PREVIOUS NTRIALS:              421
PREVIOUS NTRIALS (no repeats): 349
PREVIOUS WATER DRANK: 1064.1999999999962
LAST REWARD:                   3.4000000000000004
LAST GAIN:                     4.0
LAST CONTRAST SET:             [1.0, 0.5, 0.25]
BUFFERS:                       loaded
PREVIOUS WEIGHT:               21.4
##########################################
2019-04-12 15:45:22.56 INFO     [session_params.py:215]
##########################################
ADAPTIVE VALUES FOR CURRENT SESSION

REWARD AMOUNT:      3.3000000000000003 µl
VALVE OPEN TIME:    0.11 sec
GAIN:               4.0 azimuth_degree/mm
IMPULSIVE CONTROL   OFF
##########################################
2019-04-12 15:45:23.892 INFO     [_iblrig_tasks_trainingChoiceWorld.py:90] Starting trial: 1
2019-04-12 15:45:35.545 INFO     [trial_params.py:394]
##########################################
TRIAL NUM:            1
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           0.0
STIM PROB LEFT:       0.5
RESPONSE TIME:        10.0464

TRIAL CORRECT:        True

NTRIALS CORRECT:      1
NTRIALS ERROR:        0
WATER DELIVERED:      3.3 µl
TIME FROM START:      0:00:31.528890
TEMPERATURE:          26.549999237060547 ºC
AIR PRESSURE:         1022.025634765625 mb
RELATIVE HUMIDITY:    30.9150390625 %
##########################################
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\ibluser\anaconda3\envs\iblenv\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2019-04-12 15:45:35.862 INFO     [_iblrig_tasks_trainingChoiceWorld.py:90] Starting trial: 2
2019-04-12 15:45:38.93 INFO     [trial_params.py:394]
##########################################
TRIAL NUM:            2
STIM POSITION:        -35
STIM CONTRAST:        0.5
STIM PHASE:           2.261353603751037
STIM PROB LEFT:       0.5
RESPONSE TIME:        0.5395

TRIAL CORRECT:        True

NTRIALS CORRECT:      2
NTRIALS ERROR:        0
WATER DELIVERED:      6.6 µl
TIME FROM START:      0:00:34.049750
TEMPERATURE:          26.559999465942383 ºC
AIR PRESSURE:         1021.98486328125 mb
RELATIVE HUMIDITY:    31.1181640625 %
##########################################
2019-04-12 15:45:38.392 INFO     [_iblrig_tasks_trainingChoiceWorld.py:90] Starting trial: 3
2019-04-12 15:45:41.121 INFO     [trial_params.py:394]
##########################################
TRIAL NUM:            3
STIM POSITION:        35
STIM CONTRAST:        1.0
STIM PHASE:           2.510843174742343
STIM PROB LEFT:       0.5
RESPONSE TIME:        1.1322999999999999

TRIAL CORRECT:        True

NTRIALS CORRECT:      3
NTRIALS ERROR:        0
WATER DELIVERED:      9.9 µl
TIME FROM START:      0:00:37.104594
TEMPERATURE:          26.559999465942383 ºC
AIR PRESSURE:         1021.9642333984375 mb
RELATIVE HUMIDITY:    31.1181640625 %
##########################################
2019-04-12 15:45:41.428 INFO     [_iblrig_tasks_trainingChoiceWorld.py:90] Starting trial: 4
Connected to https://alyx.cortexlab.net as Karolina_Socha
2019-04-12 15:45:56.858 INFO     [registration.py:47] creating session for C:\iblrig_data\Subjects\KS001_NPx\2019-04-10\001
Traceback (most recent call last):
  File "..\..\..\create_session.py", line 33, in <module>
    main()
  File "..\..\..\create_session.py", line 21, in main
    create(IBLRIG_DATA, dry=False)
  File "c:\ibllib\python\alf\one_iblrig.py", line 41, in create
    rc.create_sessions(root_data_folder, dry=dry)
  File "c:\ibllib\python\oneibl\registration.py", line 49, in create_sessions
    status_str = self.register_session(flag_file.parent, file_list=False)
  File "c:\ibllib\python\oneibl\registration.py", line 24, in func_wrapper
    f = func(self, sessionpath, *args, **kwargs)
  File "c:\ibllib\python\oneibl\registration.py", line 100, in register_session
    project = self.one.alyx.rest('projects', 'read', pname[0])
IndexError: list index out of range

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
```

**Comment by nbonacchi** [comment]
@oliche Transferred issue to ibllib:
  - registration should log failure to extract and skip to next in line not break.
