### ISSUE TITLE
extract_session.py:103 failed extraction

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/ibllib#70]
During registration there was issue with one session KS005. Training was dopne on rig2 (trainingChoiceWorld protocol).

```
2019-04-12 16:59:40.406 ERROR    [extract_session.py:103] ```
C:\globus_server\Subjects\KS005\2019-04-12\001 failed extraction
    311672Traceback (most recent call last):
  File "c:\ibllib\python\alf\extract_session.py", line 95, in bulk
    from_path(p.parent, force=True, save=save)
  File "c:\ibllib\python\alf\extract_session.py", line 31, in func_wrapper
    f = func(sessionpath, *args, **kwargs)
  File "c:\ibllib\python\alf\extract_session.py", line 77, in from_path
    training_wheel.extract_all(session_path, bp_data=data, save=save)
  File "c:\ibllib\python\alf\extractors\training_wheel.py", line 333, in extract_all
    data = get_wheel_data(session_path, bp_data=bp_data, save=save)
  File "c:\ibllib\python\alf\extractors\training_wheel.py", line 147, in get_wheel_data
    df = raw.load_encoder_positions(session_path)
  File "c:\ibllib\python\ibllib\io\raw_data_loaders.py", line 191, in load_encoder_positions
    return _groom_wheel_data(data, label='_iblrig_encoderPositions.raw.ssv', path=path)
  File "c:\ibllib\python\ibllib\io\raw_data_loaders.py", line 310, in _groom_wheel_data
    elif 32 - np.log2(data['re_ts'][i] - data['re_ts'][i + 1]) < 0.2:
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\site-packages\pandas\core\indexes\base.py", line 4374, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 311672
```

```

**Comment by oliche** [comment]
This is a wheel extraction issue.
 Just continue to run your extractions/registrations as usal and I'll get the data to have a look at what is going on.

**Comment by oliche** [comment]
I think this is an old thing that is not on the latest master because I couldn't reproduce this using 0.4.35.
Anyway we moved to a mandatory release 0.5.0 so let me know how it goes if you re-extract using this code base.
