### ISSUE TITLE
MemoryError during compression video files

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/ibllib#75]
I run compression command line for video files in training rigs and got this message:
(python C:\ibllib\python\alf\one_iblrig.py compress_video C:\globus_server\Subjects). I have not made working this part yest so any data from cortexlab is without videos. 

```
(iblenv) C:\iblrig>python C:\ibllib\python\alf\one_iblrig.py compress_video C:\globus_server\Subjects
C:\globus_server\Subjects\KS002\2019-06-06\003\raw_video_data\_iblrig_leftCamera.raw.avi
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\IBLuser\Anaconda3\envs\iblenv\lib\subprocess.py", line 1238, in _readerthread
    buffer.append(fh.read())
MemoryError

```
This is to compress and register video files from training rigs and upload on flatiron.

**Comment by oliche** [comment]
2d67df545d3ce0ad09199639038cb3e486d4955c Fixes it, no stat option on the ffmpeg command to avoid accruing too much memory in the subprocess call.

Solution is to update ibllib to 0.5.5 or newer, thanks for reporting it !

**Comment by karolinasocha** [comment]
I removed and installed ibllib again but when I tried to start training trainingChoiceWorld I got message that not a git repository (or any of the parent directories): .git. .

```
Finding pybpod folder...
Launching pybpod...
libpng warning: iCCP: known incorrect sRGB profile
12/06/2019 04:41:20 | WARNING | 4504 | pyforms_generic_editor.plugins.loader | install_plugins | Plugins path was not defined by user
libpng warning: iCCP: known incorrect sRGB profile
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\_iblrig_tasks_trainingChoiceWorld.py", line 20, in <module>
    sph = SessionParamHandler(task_settings, user_settings)
  File "C:\iblrig_params\IBL\tasks\_iblrig_tasks_trainingChoiceWorld\session_params.py", line 47, in __init__
    board=self.PYBPOD_BOARD, make=make)
  File "C:\iblrig_params\path_helper.py", line 35, in __init__
    self.IBLLIB_VERSION_TAG = self._get_version_tag(self.IBLLIB_FOLDER)
  File "C:\iblrig_params\path_helper.py", line 210, in _get_version_tag
    "--points-at", "HEAD"]).decode().strip()
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\ibluser\anaconda3\envs\iblenv\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'tag', '--points-at', 'HEAD']' returned non-zero exit status 128.
Connected to https://alyx.cortexlab.net as Karolina_Socha
done
```
