### ISSUE TITLE
Spike sorting task can't get version number

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibllib#897]
```
2024-12-06 03:30:14 INFO     tasks.py:409  All input files found: running task
2024-12-06 03:30:14 INFO     tasks.py:242  Setup value is: True
2024-12-06 03:30:14 ERROR    tasks.py:269  Traceback (most recent call last):
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/ibl-sorter/.venv/lib/python3.11/site-packages/ibllib/pipes/tasks.py", line 259, in run
    outputs = self._run(**kwargs)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/ibl-sorter/.venv/lib/python3.11/site-packages/ibllib/pipes/ephys_tasks.py", line 772, in _run
    sorter_dir = self._run_iblsort(ap_file)  # runs the sorter, skips if it already ran
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/ibl-sorter/.venv/lib/python3.11/site-packages/ibllib/pipes/ephys_tasks.py", line 718, in _run_iblsort
    run_version = self._fetch_iblsorter_run_version(log_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/ibl-sorter/.venv/lib/python3.11/site-packages/ibllib/pipes/ephys_tasks.py", line 703, in _fetch_iblsorter_run_version
    version = re.sub(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])', '', version.group(1))
                                                                   ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2024-12-06 03:30:14 INFO     tasks.py:270  Job <class 'ibllib.pipes.ephys_tasks.SpikeSorting'> errored
2024-12-06 03:30:14 INFO     tasks.py:284  N outputs: 0
2024-12-06 03:30:14 INFO     tasks.py:285  --- 0.2926473617553711 seconds run-time ---
(.venv) (base) ibladmin@iblserver:/mnt/s0/spikesorting$ ls
```

Sometimes the version number can't be read correctly from the log file. Should there be a marker file ? At the very least there should be some error management here.

**Comment by oliche** [comment]
Fixed in e39d1e42865073b4b0cb5fe79980c4434323a89e
